# fly.toml app configuration file generated for gvsu-cis658-hw4-html-css-patient-flower-1336 on 2025-01-16T21:31:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gvsu-cis658-hw4-html-css-patient-flower-1336'
primary_region = 'ord'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
